on:
  watch:
    types: [ started ] # Star event
    
jobs:
  my_service:
    services:
      nginx:
        
        image: nginx
        ports:
          - 4242:80
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: curl -Is http://localhost:4242 | grep "HTTP/1.1 200 OK"
